# (c) Srevin Saju 2020. All rights reserved
# Licensed under MIT License
# Continuous Integration to release configured AppImages for Altus

name: Continuous

on:
  workflow_dispatch:
  push:
    tags:
      - "*.*"

jobs:
  AppImage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Enable Corepack
        run: corepack enable

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "yarn"

      - name: Current Directory Structure
        run: |
          ls 
          git describe --tags --always

      - name: Build Altus
        run: |
          corepack enable
          yarn install
          yarn run make -p linux

      - name: Upload Appimage
        uses: actions/upload-artifact@v4.4.0
        with:
          name: AppImage
          path: "out/make/*.AppImage"

  Darwin:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Enable Corepack
        run: corepack enable

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "yarn"

      - name: Current Directory Structure
        run: |
          ls 
          git describe --tags --always

      - name: Install dependencies
        run: |
          corepack enable
          yarn install

      # forge uses electron-installer-dmg for making the dmg, which
      # internally uses appdmg which uses macos-alias, and for whatever
      # reason, the node-gyp addon that it depends on is not correctly
      # built which causes an error when running the make command.
      # so we build it ourselves here. note: it seems to require node 18,
      # does not build with node 22
      - name: Fix macos-alias dep
        run: |
          cd ./node_modules/macos-alias
          yarn node-gyp configure
          yarn node-gyp build

      - name: Build Altus
        run: |
          yarn run make -p darwin --arch x64
          yarn run make -p darwin --arch arm64

      - name: Upload DMG
        uses: actions/upload-artifact@v4.4.0
        with:
          name: DMG
          path: "out/make/*.dmg"

  Windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Enable Corepack
        run: corepack enable

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Current Directory Structure
        run: |
          ls 
          git describe --tags --always

      - name: Build Altus
        run: |
          corepack enable
          yarn install
          yarn run make -p win32

      - name: Upload EXE
        uses: actions/upload-artifact@v4.4.0
        with:
          name: EXE
          path: "out/make/*.exe"

  Release:
    needs: [AppImage, Windows, Darwin]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v4.1.7

      - name: Release
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          prerelease: false
          files: |
            AppImage
            DMG
            EXE

          repo_token: ${{ secrets.GITHUB_TOKEN }}
